### ISSUE TITLE
FavoriteAllFiles - Error

### ISSUE THREAD

**Issue by DeadLyBro** [ppebb/shelter-plugins#1]
When I hover contextmenu item named: "Add To Favorites"
it give error:
![Screenshot_1](https://github.com/ppebb/shelter-plugins/assets/31214077/e1d0f62a-7d7b-44cc-a6b7-93c00cdf356a)
~~And where is these files? How can I find em? ( I mean if I click "Add To Favorites" button, I'm not meaning error. )~~

**Comment by DeadLyBro** [comment]
Oh I find, it's favoriting to "Gifs".

**Comment by ppebb** [comment]
I'm unable to reproduce this issue on my end. Do you know what type of file you were specifically right clicking on and if that type of file consistently causes the error, or is it all files for you?

**Comment by DeadLyBro** [comment]
> I'm unable to reproduce this issue on my end. Do you know what type of file you were specifically right clicking on and if that type of file consistently causes the error, or is it all files for you?

I tried to Embed image. (OwO Bot Embed image)

**Comment by DeadLyBro** [comment]
And its working with image and gif only?

**Comment by ppebb** [comment]
Videos are supported too. I've never tested with a bot embed so I'm not sure if that's the issue, but I'll give it a shot.

**Comment by ppebb** [comment]
Seems like bot embeds work fine for me (no clue what the owo bot is but others work fine). Could you send a message link and a server invite (if it's a public message) or add me on discord (just `ppeb`) and get it to me that way?

**Comment by DeadLyBro** [comment]
Favoriting works, but like I said, just hovering throws error like this: 
![Screenshot_1](https://github.com/ppebb/shelter-plugins/assets/31214077/e1d0f62a-7d7b-44cc-a6b7-93c00cdf356a)
If you can't fix, it's fine but it will throw errors everytime users hover contextmenu "Add To Favorites" item and item can't highlight because of that.

**Comment by ppebb** [comment]
Yeah I just can't get it to error on hover, highlighting works on everything I right click.

**Comment by DeadLyBro** [comment]
I disabled other plugins but it give error again, nvm I'm closing this issue or you can.
